### ISSUE TITLE
Security concerns around sending session ID by default

### ISSUE THREAD

**Issue by stecman** [getsentry/raven-php#179]
Currently, any message captured during an HTTP request is sent with a full copy of the request cookies, as well as sending the value of `session_id()` if user context isn't provided to the instance of `Raven_Client`. Sending the value of the session ID doesn't provide any useful information for debugging and opens up a number of attack vectors for session hijacking (it's also [mentioned in the Sentry docs](http://sentry.readthedocs.org/en/latest/developer/client/index.html#scrubbing-data) as something to avoid). Additionally, there's currently no clean way for users of this library to scrub data before it gets pushed to Sentry, which would be useful for removing other sensitive information that is application specific (eg. login 'remember me' cookies).

I propose these changes:

* Hide the value or remove the session cookie from the copy of `$_COOKIES` ([line 328](https://github.com/getsentry/raven-php/blob/17e32797b0698d6a620a60b6b5f8a37306bf4e43/lib/Raven/Client.php#L328))
* Remove sending session ID as part of the default user data in `get_user_data()` ([line 350](https://github.com/getsentry/raven-php/blob/17e32797b0698d6a620a60b6b5f8a37306bf4e43/lib/Raven/Client.php#L350))
* Add some form of customisable outgoing data sanitisation/filter to `Raven_Client` that doesn't require extending the class.

There are a number of ways the last point could be implemented, but I'd probably approach it with something like a `Raven_Filter` interface that can be added to a client: `Raven_Client::addFilter($filter)`. Data would be run through an instance's list of filters before being sent to Sentry.

Would a PR or two with these changes be accepted?

**Comment by smazurov** [comment]
point 3 is covered by [Processors](https://github.com/getsentry/raven-php#processors), it in fact how it currently [removes passwords and secrets](https://github.com/getsentry/raven-php/blob/560b2ac702bbdf47ad8035bdb4a97c73e2cf0648/lib/Raven/SanitizeDataProcessor.php).

Sending `session_id` isn't ideal (although its also not ideal to store that directly in the cookie), but its used as a simple way to uniquely identify users, much like a `GUID` does in iOS. If a single user is generating errors, even if you can't identify them from an event, you might be able to co-relate and recreate. That information is useful IMO. An improvement can/should be made to further remove the data from being able to uniquely ID the user. 

For cookies, since the session cookie name isn't standard, its impossible to have a one size fits all solution. Adding your own processor to remove that info should be enough, and is indeed what they recommend in the docs.

As far as PR, while I have no direct connection to owners of the repo, but they seem to be receptive to PRs, as they have a very good merge rate.

**Comment by stecman** [comment]
Thanks, I must have overlooked processors.

> For cookies, since the session cookie name isn't standard, its impossible to have a one size fits all solution.

While PHP's session functionality is not guaranteed to be used, I would say that removing the cookie named in `ini_get('session.name')` would cover a decent percentage of cases and seems like a sane default.
