### ISSUE TITLE
just signed up for sentry and installed integration using master, not seeing stack traces for errors

### ISSUE THREAD

**Issue by sneak** [getsentry/raven-php#241]
see above. seeing the errors, context, environment - but no stack traces. what gives?

**Comment by dcramer** [comment]
@sneak are the errors actually exceptions? its possible they simply dont have the context

it's also possible theres data getting thrown away due to something. I assume there's no "There were errors processing this event" blurb at the top of the page?

If this is on getsentry.com, mind dropping a link to the event here?

**Comment by sneak** [comment]
https://app.getsentry.com/align-commerce/appserver/group/89703247/

**Comment by dcramer** [comment]
@sneak i think this is an old-style error. You'll see theres a single line in the stacktrace. It's a bit hard to spot just because of the large message.

**Comment by sneak** [comment]
old-style errors don't get stack traces? so there's no way to get a stack trace from an arbitrary point in an app without throwing an exception that goes uncaught and terminating the app?

**Comment by dcramer** [comment]
@sneak sorry edited my comment :)

You have a full stacktrace in your example. I'm assuming you're throwing this at the top of the app so there's actually no depth to it.

If you had something like this (psuedocode):

function foo() { function bar() { function baz() { throw new Exception("foo"); }() }() } ()

You would get a more rich stacktrace as the error is happening deeper.

**Comment by sneak** [comment]
nope, it's not at the top.

**Comment by sneak** [comment]
i get them for exceptions, just not for errors/warnings

**Comment by dcramer** [comment]
@sneak if you can provide a test case that proves otherwise we can dig more, but we're just calling to PHP's stack handlers here:

https://github.com/getsentry/raven-php/blob/master/lib/Raven/Client.php#L260

It's also important to know that *actual* exceptions are different in PHP than old-style warnings. Old-style warnings don't have full stacktraces, they only have the last frame.

**Comment by sneak** [comment]
that answers my question, thank you.

**Comment by sneak** [comment]
it would be super awesome if there were a feature in raven to send a "debug message" at level debug to sentry with a full stack trace and local vars etc but continue script execution for resolving weird app issues. i thought throwing a warning would do this but apparently not.

**Comment by sneak** [comment]
(it's my understanding that errors stop execution)
